/* ===========================================================================
   POLISH STUDENT SOCIETIES IN THE UK
   ---------------------------------------------------------------------------
   Source: "Polish Societies List 2026" spreadsheet.
   Each entry becomes a pin on the members map and a card below it.

   name       — society name (cards are sorted alphabetically at runtime)
   uni        — city / nation shown under the name
   lat, lng   — coordinates of the university campus the society belongs to
   instagram  — handle without the @ (the URL is built automatically)
   email      — society email, or "" if they don't publish one
   logo       — file in assets/polsocs/
   active     — is the society currently running?
   member     — current member of the Federation
   pastMember — has been a member in the past
   =========================================================================== */

const SOCIETIES = [
  {
    name: "Aberdeen University Polish Society",
    uni: "Aberdeen, Scotland",
    lat: 57.1645, lng: -2.1011,
    instagram: "ausapolishsociety",
    email: "polish@ausa.org.uk",
    logo: "aberdeen.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "Bath Polish Society",
    uni: "Bath, England",
    lat: 51.3801, lng: -2.3266,
    instagram: "bathpolishsoc",
    email: "polishsoc@bath.ac.uk",
    logo: "bath.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "Cambridge Polish Society",
    uni: "Cambridge, England",
    lat: 52.2053, lng: 0.1167,
    instagram: "cupolsoc",
    email: "cupolsoc@gmail.com",
    logo: "cambridge.jpg",
    active: true, member: false, pastMember: true,
  },
  {
    name: "Cardiff Polish Society",
    uni: "Cardiff, Wales",
    lat: 51.4874, lng: -3.1793,
    instagram: "polishsocietycardiff",
    email: "PolishSociety@cardiff.ac.uk",
    logo: "cardiff.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "City Polish Society",
    uni: "London, England",
    lat: 51.5279, lng: -0.1029,
    instagram: "citypolsoc",
    email: "",
    logo: "city.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "Durham University Polish Society",
    uni: "Durham, England",
    lat: 54.7736, lng: -1.5757,
    instagram: "polsocdurham",
    email: "durhampolishsociety@gmail.com",
    logo: "durham.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "Edinburgh University Polish Society",
    uni: "Edinburgh, Scotland",
    lat: 55.9445, lng: -3.1892,
    instagram: "edipolsoc",
    email: "pol.soc.ed@gmail.com",
    logo: "edinburgh.jpg",
    active: true, member: true, pastMember: true,
  },
  {
    name: "Essex Polish Society",
    uni: "Colchester, England",
    lat: 51.8787, lng: 0.9481,
    instagram: "essexpolishsociety",
    email: "",
    logo: "essex.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "Exeter Polish Society",
    uni: "Exeter, England",
    lat: 50.7371, lng: -3.5340,
    instagram: "exeterpolishsociety",
    email: "polish@groups.exeterguild.com",
    logo: "exeter.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "Huddersfield University Polish Society",
    uni: "Huddersfield, England",
    lat: 53.6432, lng: -1.7787,
    instagram: "polskahud",
    email: "u2365935@unimail.hud.ac.uk",
    logo: "huddersfield.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "Imperial Polish Society",
    uni: "London, England",
    lat: 51.4988, lng: -0.1749,
    instagram: "imperialpolsoc",
    email: "pol-soc@imperial.ac.uk",
    logo: "imperial.jpg",
    active: false, member: false, pastMember: true,
  },
  {
    name: "KCL Polish Society",
    uni: "London, England",
    lat: 51.5115, lng: -0.1160,
    instagram: "kclpolishsociety",
    email: "hello.kclpolishsociety@gmail.com",
    logo: "kings.jpg",
    active: true, member: true, pastMember: true,
  },
  {
    name: "Kent Polish Society",
    uni: "Canterbury, England",
    lat: 51.2977, lng: 1.0699,
    instagram: "ukc.polishsoc",
    email: "polishsoc@ksu.co.uk",
    logo: "kent.jpg",
    active: true, member: false, pastMember: true,
  },
  {
    name: "Lancaster University Polish Society",
    uni: "Lancaster, England",
    lat: 54.0100, lng: -2.7857,
    instagram: "lu.polishsociety",
    email: "polish.su@groups.lancaster.ac.uk",
    logo: "lancaster.jpg",
    active: true, member: false, pastMember: true,
  },
  {
    name: "Leeds University Polish Society",
    uni: "Leeds, England",
    lat: 53.8067, lng: -1.5550,
    instagram: "polsocleeds",
    email: "polish@luu.group",
    logo: "leeds.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "Loughborough University Polish Society",
    uni: "Loughborough, England",
    lat: 52.7658, lng: -1.2295,
    instagram: "lsupolishsociety",
    email: "LSUPolSoc@outlook.com",
    logo: "loughborough.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "LSE Polish Society",
    uni: "London, England",
    lat: 51.5144, lng: -0.1165,
    instagram: "lsesu.pbs",
    email: "info@polish-business.org",
    logo: "lse.jpg",
    active: true, member: false, pastMember: true,
  },
  {
    name: "Manchester University Polish Society",
    uni: "Manchester, England",
    lat: 53.4668, lng: -2.2339,
    instagram: "polsocmanchester",
    email: "polish.society@manchesterstudentsunion.com",
    logo: "manchester.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "Oxford University Polish Society",
    uni: "Oxford, England",
    lat: 51.7534, lng: -1.2540,
    instagram: "oxpolsoc",
    email: "oxfordpolishsoc@gmail.com",
    logo: "oxford.jpg",
    active: true, member: false, pastMember: true,
  },
  {
    name: "QMUL Polish Society",
    uni: "London, England",
    lat: 51.5246, lng: -0.0384,
    instagram: "qmulpolsoc",
    email: "polishsociety@qmsu.org",
    logo: "queen-mary.jpg",
    active: true, member: true, pastMember: true,
  },
  {
    name: "Sheffield University Polish Society",
    uni: "Sheffield, England",
    lat: 53.3811, lng: -1.4879,
    instagram: "polishsocietysheffield",
    email: "polish.society@sheffield.ac.uk",
    logo: "sheffield.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "Southampton Polish Society",
    uni: "Southampton, England",
    lat: 50.9350, lng: -1.3960,
    instagram: "polsoc.soton",
    email: "polsoc@soton.ac.uk",
    logo: "southampton.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "St Andrews Polish Society",
    uni: "St Andrews, Scotland",
    lat: 56.3403, lng: -2.7936,
    instagram: "sta.polsoc",
    email: "polishsocmail@st-andrews.ac.uk",
    logo: "st-andrews.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "UCL Polish Society",
    uni: "London, England",
    lat: 51.5246, lng: -0.1340,
    instagram: "uclpolishsociety",
    email: "polishsociety@ucl.ac.uk",
    logo: "ucl.jpg",
    active: true, member: false, pastMember: true,
  },
  {
    name: "University of Glasgow Central & Eastern European Society",
    uni: "Glasgow, Scotland",
    lat: 55.8721, lng: -4.2882,
    instagram: "uofg.ceessoc",
    email: "ceessociety@gmail.com",
    logo: "glasgow.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "University of Leicester Polish Society",
    uni: "Leicester, England",
    lat: 52.6215, lng: -1.1240,
    instagram: "uol.polishsociety",
    email: "",
    logo: "leicester.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "University of Liverpool Polish Society",
    uni: "Liverpool, England",
    lat: 53.4058, lng: -2.9660,
    instagram: "uolpolsoc",
    email: "polish@society.liverpoolguild.org",
    logo: "liverpool.jpg",
    active: true, member: false, pastMember: true,
  },
  {
    name: "University of Nottingham Polish Society",
    uni: "Nottingham, England",
    lat: 52.9385, lng: -1.1957,
    instagram: "uon_polish",
    email: "polish@uonsu.com",
    logo: "nottingham.jpg",
    active: true, member: false, pastMember: true,
  },
  {
    name: "University of York Polish Society",
    uni: "York, England",
    lat: 53.9465, lng: -1.0524,
    instagram: "uoypolsoc",
    email: "polishsociety@yorksu.org",
    logo: "york.jpg",
    active: true, member: false, pastMember: false,
  },
  {
    name: "Warwick Polish Society",
    uni: "Coventry, England",
    lat: 52.3793, lng: -1.5615,
    instagram: "polsoc.warwick",
    email: "polishsocietywarwickuni@gmail.com",
    logo: "warwick.jpg",
    active: true, member: false, pastMember: true,
  },
];
