/**
 * The cross product of published standard events × locales.
 *
 * Eleventy's `pagination` walks ONE data set, but a standard-event page is
 * identified by two things: which event, and which language. Building the pairs
 * here keeps `src/event.njk` to a single `pagination` block instead of nested
 * templates or a second build pass.
 *
 * Only `event_family: standard` is included. The Polish Business Forum is a
 * separate family with its own template and extension schema, and is
 * deliberately not generated by this template.
 */

"use strict";

const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");

const EVENTS_DIR = path.join(__dirname, "..", "..", "content", "events");
const LOCALES = require("./locales.json");

module.exports = () => {
  if (!fs.existsSync(EVENTS_DIR)) return [];

  const events = fs
    .readdirSync(EVENTS_DIR)
    // .sort() keeps the build deterministic: readdir order is filesystem
    // dependent and would otherwise vary between machines.
    .sort()
    .filter((f) => /\.ya?ml$/i.test(f))
    .map((f) => ({
      ...(yaml.load(fs.readFileSync(path.join(EVENTS_DIR, f), "utf8")) || {}),
      _source: `content/events/${f}`,
    }))
    .filter((e) => e.published === true && e.event_family === "standard")
    .sort((a, b) => (a.order - b.order) || (String(a.slug) < String(b.slug) ? -1 : 1));

  const pairs = [];
  for (const event of events) {
    for (const locale of LOCALES) {
      pairs.push({ event, locale });
    }
  }
  return pairs;
};
